### ISSUE TITLE
Pre-training model download problem

### ISSUE THREAD

**Issue by 1129ljc** [hitachinsk/FGT#11]
Thanks for sharing the video inpainting project, there is a problem downloading the pre-trained model.
![1660182198861](https://user-images.githubusercontent.com/38351525/184051002-4e3a171b-f64c-4a23-bdad-0a9f659436dd.jpg)

**Comment by hitachinsk** [comment]
Oh, it's my fault. I have updated the access permission. Can you download now?

**Comment by 1129ljc** [comment]
Thanks for the help, the  pre-trained model is now available for download!

**Comment by hitachinsk** [comment]
Okay, I will close this issue. If you like our work, please give us a star, thank you!
