### ISSUE TITLE
Add python to env creation so correct pip will be used

### ISSUE THREAD

**Issue by R4ZZ3** [hitachinsk/FGT#14]
In the installation process
"conda create -n FGT
conda activate FGT
pip install -r requirements.txt
pip install imageio-ffmpeg"

Add step to install pip and python to conda environment to make sure correct pip is used and packages are installed to FGT environment. This can be caveat to some young developers if not done correctly and if ROOT envs pip is accidentally used
--> 
"conda create -n FGT python=3.x"
conda activate FGT
pip install -r requirements.txt
pip install imageio-ffmpeg"

**Comment by hitachinsk** [comment]
Thanks for your advise, I will modify the corresponding parts.

**Comment by hitachinsk** [comment]
I have modified the installation process, and I will test this part.

**Comment by hitachinsk** [comment]
I have tested this part, thanks for your advise. If you still have other advise that is not related to the logic of the codes, please make a pull request, so that such bugs can be quickly fixed.
