### ISSUE TITLE
yaml.load fails in wsl, change load method to make it work

### ISSUE THREAD

**Issue by R4ZZ3** [hitachinsk/FGT#15]
When testing with the given test script (video_inpainting.py) the following happens:

With PyYAML==6.0 on Windows using vs code in WSL2 I get error:
![image](https://user-images.githubusercontent.com/25264037/185467142-c47e1d9b-67d6-465c-bd92-bd2cc54738ee.png)

According to this it now needs to explicitly tell Loader object or either use safe_load / full _load methods as explained here: https://bobbyhadz.com/blog/python-typeerror-load-missing-1-required-positional-argument-loader

When I change to yaml.full_load(f) it works

**Comment by hitachinsk** [comment]
Thanks for your advise. When I tested the scripts on my own server, the `yaml.load` only threw warnings, but it seems to be an error in other newer environments. I will fix it.

**Comment by hitachinsk** [comment]
I have modified the load function to `yaml.full_load`, hope it works for you.
