### ISSUE TITLE
FGT model config problem

### ISSUE THREAD

**Issue by OHaiYo-lzy** [hitachinsk/FGT#16]
When I tried to train your FGT model ,it occured to me that I`m missing the right  .yaml config file in flowCheckPoint dir
which caused this to happen

`RuntimeError: Error(s) in loading state_dict for Model:
	Missing key(s) in state_dict:`

..
Could pls release the right and corresponding config file?

**Comment by hitachinsk** [comment]
I have appended the config (yaml) file in the pretrained models. Please redownload the `weight.zip` as instructed in the `README`. I also update the corresponding codes, therefore you also need to update the codebase. Sorry for the late reply.

**Comment by OHaiYo-lzy** [comment]
Thx for your reply.
But after I tried to do so , the same problem occured that
firstly:
`config['resBlocks'], config['use_bias'], config['conv_type'], config['multi_out'],
KeyError: 'multi_out'`

so I add multi_out: 0 into the config.yaml, then:
`RuntimeError: Error(s) in loading state_dict for Model:
	Missing key(s) in state_dict: "net.edgeDetector.projection.featureConv.weight", "net.edgeDetector.projection.featureConv.bias", "net.edgeDetector.mid_layer_1.featureConv.weight", "net.edgeDetector.mid_layer_1.featureConv.bias", "net.edgeDetector.mid_layer_2.featureConv.weight", "net.edgeDetector.mid_layer_2.featureConv.bias", "net.edgeDetector.out_layer.featureConv.weight", "net.edgeDetector.out_layer.featureConv.bias". `

or multi_out: 1:
`RuntimeError: Error(s) in loading state_dict for Model:
	Missing key(s) in state_dict: "net.out4.featureConv.weight", "net.out4.featureConv.bias", "net.out2.featureConv.weight", "net.out2.featureConv.bias", "net.edgeDetector.projection.featureConv.weight", "net.edgeDetector.projection.featureConv.bias", "net.edgeDetector.mid_layer_1.featureConv.weight", "net.edgeDetector.mid_layer_1.featureConv.bias", "net.edgeDetector.mid_layer_2.featureConv.weight", "net.edgeDetector.mid_layer_2.featureConv.bias", "net.edgeDetector.out_layer.featureConv.weight", "net.edgeDetector.out_layer.featureConv.bias". `

Could pls look into that and help to fix that?
Thx!!

**Comment by OHaiYo-lzy** [comment]
By the way ,I noticed that you updated the flow_net model file to lafc_single file , But didn`t update the corresponding network file.Hopefully be handled,Thx

**Comment by hitachinsk** [comment]
I checked the details, and found the problem was caused by the wrong model I uploaded. I have uploaded the right weights and modified the corresponding codes, please download this project again. I tested the codes on my own server, and the training process could be executed. If you have any problems, please reply under this comment. Thanks for pointing out my mistake.
