### ISSUE TITLE
test result resolution

### ISSUE THREAD

**Issue by wangdi9** [hitachinsk/FGT#23]
Is the resolution of the final output video image of the algorithm different from that of the input image? Same or bigger or smaller?how to adjust parameter for adapting my poor GPU memory(6G)？

**Comment by hitachinsk** [comment]
The resolution of the final output video is the same as that of the input image. If you want to get the results as original resolution but the GPU memory is limited, I recommend to increase the parameter in https://github.com/hitachinsk/FGT/blob/6bfc5dcb1778f650735d5a070974ca8318f1866f/tool/video_inpainting.py#L649 or decrease the parameter in https://github.com/hitachinsk/FGT/blob/6bfc5dcb1778f650735d5a070974ca8318f1866f/tool/video_inpainting.py#L651

If you want to change the resolution, please adjust the parameters in https://github.com/hitachinsk/FGT/blob/6bfc5dcb1778f650735d5a070974ca8318f1866f/tool/video_inpainting.py#L641
and
https://github.com/hitachinsk/FGT/blob/6bfc5dcb1778f650735d5a070974ca8318f1866f/tool/video_inpainting.py#L642

**Comment by wangdi9** [comment]
very very thanks
