### ISSUE TITLE
Default watermark removal mode config not work very well

### ISSUE THREAD

**Issue by cpfy** [hitachinsk/FGT#25]
Hi, thanks for uploading this great code. I really enjoy your work.

I ran the demo video in object-removal and watermark removal modes respectively, and found that the watermark removal results have residual images and are not stable enough.

I also tried to use the parameters of object-removal
```
consistencyThres: 5
flow_mask_dilates: 12
frame_dilates: 4
```
this time the generated result has some improvement.

I am confused about the default parameters used in watermark_removal, is there any way to improve the quality by adjusting the parameters? Thanks.

**Comment by hitachinsk** [comment]
We tried some parameters on the DAVIS dataset, and found the current parameter set (the default config of watermark removal) could achieve the best objective performance. We select PSNR as our default metric.

Although the default parameter configuration could achieve the best PSNR performance, it does not mean it could also achieve the best subjective performance on **each video**. Therefore, it's very normal that the newly designed parameter set could achieve better performance on some of the videos.

**Comment by cpfy** [comment]
Thanks for the detailed explanation! I'll try it on my own video.
