### ISSUE TITLE
T dimension problems in encoders

### ISSUE THREAD

**Issue by cr7wkx** [hitachinsk/FGT#31]
inputs = inputs.view(b * t, self.in_channels, h, w)
enc_feats = self.frame_endoder(inputs)
Why is the t dimension multiplied on the batch dimension and not on the channel dimension？Can you explain it?Thank you

**Comment by hitachinsk** [comment]
We regard each image as a sample. Therefore, if the batch size is `b` and temporal dimension is `t`, we have `b*t` samples for processing. Since the encoder processes each sample in the same manner, we multiply the temporal dimension on the batch dimension.

**Comment by cr7wkx** [comment]
So the encoder will only extract the feature information of each frame, not the time information between frames, right?

**Comment by hitachinsk** [comment]
Yes, such design follows the implementation of STTN and Fuseformer. We noted the frame-wise encoder for feature extraction in video inpainting harms the performance and tried to solve the problem with flow guidance in the encoder. For more details, you can read the extended version of FGT. Here is the paper link: [FGT++](https://arxiv.org/pdf/2301.10048.pdf).

**Comment by cr7wkx** [comment]
> Yes, such design follows the implementation of STTN and Fuseformer. We noted the frame-wise encoder for feature extraction in video inpainting harms the performance and tried to solve the problem with flow guidance in the encoder. For more details, you can read the extended version of FGT. Here is the paper link: [FGT++](https://arxiv.org/pdf/2301.10048.pdf).

Ok，thank you for your patient reply.
