### ISSUE TITLE
output video size

### ISSUE THREAD

**Issue by AppleMax1992** [hitachinsk/FGT#34]
Dear Author,
It is a great project. And I meet a problem, can I set the output size of the video? i mean the height and the width.

**Comment by AppleMax1992** [comment]
I try to add arguments like --imgW 480 --imgH 853, however, it failed. Do we have a limit border for width and height?

**Comment by hitachinsk** [comment]
Due to the stride of encoder and decoder, the width and height should be divisible by 4.

**Comment by AppleMax1992** [comment]
Thanks for your notification.
Great answer, and this issue should be closed.
