### ISSUE TITLE
The flow propagation

### ISSUE THREAD

**Issue by diaodeyi** [hitachinsk/FGT#35]
Hi , thanks for great work! The flow propagation mentioned in paper seems to be missing in the released code, it doesn't matter?

**Comment by hitachinsk** [comment]
Our repository contains the  flow-guided content propagation. Please refer https://github.com/hitachinsk/FGT/blob/master/tool/get_flowNN_gradient.py for more details.

**Comment by diaodeyi** [comment]
The flow-guided content propagation is just for inference. In this why, the input setting is different for training and inference?

**Comment by hitachinsk** [comment]
Yes, the flow-guided content propagation is just for inference, and there is slight difference between the training and the inference procedure.
