### ISSUE TITLE
About square mask settings

### ISSUE THREAD

**Issue by jinsuyoo** [hitachinsk/FGT#36]
Hope everything is well with you!

Recently I've been trying to reproduce FGT's performance on square mask settings but failed. Under our own setting (by using "object_removal.yaml" config), we face that the FGT's performance on Youtube-VOS is lower than STTN about 1dB, while outperforming STTN on the DAVIS dataset. Can you share the config for square settings if exist?

Thank you for open-sourcing your great work :)

Best,

Jinsu

**Comment by hitachinsk** [comment]
In square mask setting, we adopt the waterwark_removal.yaml as the default config. Please use this config to reproduce the results.
