### ISSUE TITLE
Cuda OOM (1k+ frame video) on A100

### ISSUE THREAD

**Issue by smandava98** [hitachinsk/FGT#39]
Hi @hitachinsk. Thanks for the great work.

Is there any recommendations you or anyone else can give on how to solve a Cuda OOM issue using FGT? I tried experimenting with allocation size as well as cleared my cache but nothing works. I see the batch size is already low. 
I'm on an A100 which should be plenty.

This line of code:

`filled_frames = FGT_model(masked_frames, selected_flows, selected_masks)`

**Comment by smandava98** [comment]
Also if I have over a thousand frames, what is the recomended sequence length if my objects are moving slowly across those frames?

**Comment by hitachinsk** [comment]
You can reduce the number of the sampled frames in each training iteration. But high resolution video inpainting is always a tough problem, maybe it's better to train on a lower resolution and enlarge the resolution gradually.

**Comment by smandava98** [comment]
Thanks @hitachinsk . I have a followup question:

What is your recommendation for fps for test videos? I am unable to find info on train/val/test info on the fps of the videos.

**Comment by hitachinsk** [comment]
We adopt 25fps videos.
