### ISSUE TITLE
supplementary material

### ISSUE THREAD

**Issue by Note-Liu** [hitachinsk/FGT#40]
May I ask where the “supplementary material” mentioned multiple times in the paper is ？

**Comment by hitachinsk** [comment]
[Here is the supplementary material.](https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136780072-supp.pdf)

**Comment by Note-Liu** [comment]
> [Here is the supplementary material.](https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136780072-supp.pdf)

Thanks for your reply ！
