### ISSUE TITLE
Constantly getting 'ValueError: need at least one array to stack' error

### ISSUE THREAD

**Issue by Sudgary003** [hitachinsk/FGT#41]
I followed the prerequisites down to the requirements. I needed to update the requirements because of conflicting dependencies. After everything installed without a hitch I ran the code to make sure everything checked out I got the error below:

![Error](https://github.com/hitachinsk/FGT/assets/51482958/06b5af09-d719-4e3f-98dc-6cf497893eaa)

Any help would be appreciated!

**Comment by saimeur** [comment]
Hi @Sudgary003,
I also had to update the requirements to avoid conflicts among librairies. I have the same error as you when I try inpainting with my own videos. How did you solve it ?

Demo's videos work just fine and my video of 3 seconds with shape (1920,1080) and output shape (480, 854) using --imgH and imgW also works fine. But once I put a video of >200 frames (~8 seconds of video) I have this error. If you have the solution feel free to share it :)
